/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.*;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author saad.ahmed
 */
public class BeginForm extends javax.swing.JFrame implements Runnable {
    
    public static String ip_address;
    public static String user;
    public static String password;
    public static String database_name;
    public static String database_type;
    public static int Ambit;
    public static int Ambit_Corporate;
    public static int Mobile;
    public static int Nimbus;
    public static int Novus;
    public static int ODS;
    public static int RDV;
    public static int Vision;
    public static int Unison;
    public static int Others;
    public static int remember_me;

    /**
     * Creates new form BeginForm
     */
    
    public BeginForm() {
        initComponents();
        
        //DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        //jLabel1.setText(dtf.format(LocalDateTime.now()));
         
        // Hiding Loader Progress Bar and Label
        prgLoader.setVisible(false);
        
          //JLabel10 imgLabel = new JLabel10(new ImageIcon("HC.png"));
          //jPanel1.add(new ImageIcon("HC.png"));
        btnImageChanger1.setBackground(Color.green);
  
    }
    
    public BeginForm(String ip, String user, String password, String database, String dbtype, int remember) {
        this.ip_address = ip;
        this.user = user;
        this.password = password;
        this.database_name = database;
        this.database_type = dbtype;
        this.remember_me = remember;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        prgLoader = new javax.swing.JProgressBar();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        txtServer = new javax.swing.JTextField();
        lblServer = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btnPing = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblDatabaseName = new javax.swing.JLabel();
        txtDatabaseName = new javax.swing.JTextField();
        lblDatabaseType = new javax.swing.JLabel();
        comboDatabaseType = new javax.swing.JComboBox();
        lblProduct = new javax.swing.JLabel();
        lblRemember = new javax.swing.JLabel();
        tglRemember = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnImageChanger1 = new javax.swing.JButton();
        btnImageChanger2 = new javax.swing.JButton();
        btnImageChanger3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        chkUnison = new javax.swing.JCheckBox();
        chkRDV = new javax.swing.JCheckBox();
        chkAmbit = new javax.swing.JCheckBox();
        chkAmbitCor = new javax.swing.JCheckBox();
        chkNovus = new javax.swing.JCheckBox();
        chkODS = new javax.swing.JCheckBox();
        chkVision = new javax.swing.JCheckBox();
        chkNimbus = new javax.swing.JCheckBox();
        chkMobile = new javax.swing.JCheckBox();
        chkOthers = new javax.swing.JCheckBox();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane5 = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setOpaque(true);

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jTabbedPane2.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Health Check Report Generator");
        setBackground(new java.awt.Color(102, 153, 255));
        setBounds(new java.awt.Rectangle(5, 5, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1037, 171, -1, -1));

        prgLoader.setStringPainted(true);
        getContentPane().add(prgLoader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));
        getContentPane().add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 237, -1, -1));
        getContentPane().add(filler3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 29, -1, -1));
        getContentPane().add(filler4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 56, -1, -1));

        txtServer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtServer.setText("172.16.0.74");
        txtServer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtServerKeyPressed(evt);
            }
        });
        getContentPane().add(txtServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 244, 33));

        lblServer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblServer.setText("Server Name");
        getContentPane().add(lblServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUser.setText("User");
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 29));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUser.setText("PIT");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 244, 31));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setText("Avanza123");
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 244, 33));

        lblPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPassword.setText("Password");
        getContentPane().add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        btnPing.setBackground(new java.awt.Color(0, 0, 204));
        btnPing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPing.setForeground(new java.awt.Color(255, 255, 255));
        btnPing.setText("PING");
        btnPing.setToolTipText("Ping the server");
        btnPing.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPing.setBorderPainted(false);
        btnPing.setFocusPainted(false);
        btnPing.setFocusable(false);
        btnPing.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPing.setInheritsPopupMenu(true);
        btnPing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPingActionPerformed(evt);
            }
        });
        getContentPane().add(btnPing, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 69, 33));

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnClear.setText("Clear All");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 112, 37));

        btnLogin.setBackground(new java.awt.Color(0, 0, 204));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setToolTipText("Click here to login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogin.setContentAreaFilled(false);
        btnLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogin.setOpaque(true);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, 400, 50));

        lblDatabaseName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDatabaseName.setText("Database Name");
        getContentPane().add(lblDatabaseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        txtDatabaseName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDatabaseName.setText("PIT_MBLUNISON");
        getContentPane().add(txtDatabaseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 244, 33));

        lblDatabaseType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDatabaseType.setText("Select Database");
        getContentPane().add(lblDatabaseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 148, 34));

        comboDatabaseType.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        comboDatabaseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select database type..", "Microsoft SQL Server", "Oracle Server", "MySql Server", "MangoDB Server", "DB/2 Server", "Redis Server" }));
        comboDatabaseType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDatabaseTypeActionPerformed(evt);
            }
        });
        getContentPane().add(comboDatabaseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 240, 34));

        lblProduct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblProduct.setText("Select Product");
        getContentPane().add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 156, -1));

        lblRemember.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblRemember.setText("Remember me?");
        getContentPane().add(lblRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 142, 36));

        tglRemember.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tglRemember.setText("OFF");
        tglRemember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglRememberActionPerformed(evt);
            }
        });
        getContentPane().add(tglRemember, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, 104, 36));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 30, 10));

        jLabel12.setBackground(new java.awt.Color(153, 153, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Discover your current problems and your potential future problems.");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 590, 50));

        btnImageChanger1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageChanger1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImageChanger1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 30, 20));

        btnImageChanger2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageChanger2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImageChanger2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 650, 30, 20));

        btnImageChanger3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageChanger3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImageChanger3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 650, 30, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PCPlus.png"))); // NOI18N
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, 590, 440));

        jLabel15.setBackground(new java.awt.Color(102, 102, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" Please Provide Login Credentials");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 620, 50));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainTitle2.png"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(120, 70));
        jLabel16.setMinimumSize(new java.awt.Dimension(120, 70));
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(120, 70));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 120));

        chkUnison.setBackground(new java.awt.Color(255, 255, 255));
        chkUnison.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkUnison.setText("Unison");
        getContentPane().add(chkUnison, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, -1, -1));

        chkRDV.setBackground(new java.awt.Color(255, 255, 255));
        chkRDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkRDV.setText("RDV");
        getContentPane().add(chkRDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        chkAmbit.setBackground(new java.awt.Color(255, 255, 255));
        chkAmbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAmbit.setText("Ambit");
        getContentPane().add(chkAmbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        chkAmbitCor.setBackground(new java.awt.Color(255, 255, 255));
        chkAmbitCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAmbitCor.setText("Ambit Corporate");
        getContentPane().add(chkAmbitCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, -1, -1));

        chkNovus.setBackground(new java.awt.Color(255, 255, 255));
        chkNovus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkNovus.setText("Novus");
        getContentPane().add(chkNovus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        chkODS.setBackground(new java.awt.Color(255, 255, 255));
        chkODS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkODS.setText("ODS");
        getContentPane().add(chkODS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        chkVision.setBackground(new java.awt.Color(255, 255, 255));
        chkVision.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkVision.setText("Vision");
        getContentPane().add(chkVision, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        chkNimbus.setBackground(new java.awt.Color(255, 255, 255));
        chkNimbus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkNimbus.setText("Nimbus");
        getContentPane().add(chkNimbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        chkMobile.setBackground(new java.awt.Color(255, 255, 255));
        chkMobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkMobile.setText("Mobile App");
        getContentPane().add(chkMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        chkOthers.setBackground(new java.awt.Color(255, 255, 255));
        chkOthers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkOthers.setText("Other");
        getContentPane().add(chkOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, -1, -1));

        jTabbedPane3.setBackground(new java.awt.Color(153, 153, 255));
        jTabbedPane3.setOpaque(true);
        getContentPane().add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 620, 540));
        getContentPane().add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 670, -1, 10));

        jTabbedPane5.setBackground(new java.awt.Color(51, 51, 255));
        jTabbedPane5.setOpaque(true);
        getContentPane().add(jTabbedPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 620, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDatabaseTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDatabaseTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDatabaseTypeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtServer.setText("");
        txtUser.setText("");
        txtPassword.setText("");
        txtDatabaseName.setText("");
        comboDatabaseType.setSelectedIndex(0);
        chkAmbit.setSelected(false);
        chkAmbitCor.setSelected(false);
        chkMobile.setSelected(false);
        chkNovus.setSelected(false);
        chkNimbus.setSelected(false);
        chkODS.setSelected(false);
        chkRDV.setSelected(false);
        chkVision.setSelected(false);
        chkUnison.setSelected(false);
        chkOthers.setSelected(false);
        tglRemember.setSelected(false);
        tglRemember.setBackground(Color.LIGHT_GRAY);
        tglRemember.setText("OFF");
    }//GEN-LAST:event_btnClearActionPerformed

    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        prgLoader.setVisible(true);
        ip_address = txtServer.getText().toString();
        user = txtUser.getText().toString();
        password = txtPassword.getText().toString();
        database_name = txtDatabaseName.getText();
        database_type = comboDatabaseType.getSelectedItem().toString();
        if(chkAmbit.isSelected()) {
            Ambit = 1;
        }
        else {
            Ambit = 0;
        }
        if(chkAmbitCor.isSelected()) {
            Ambit_Corporate = 1;
        }
        else {
            Ambit_Corporate = 0;
        }
        if(chkMobile.isSelected()) {
            Mobile = 1;
        }
        else {
            Mobile = 0;
        }
        if(chkNovus.isSelected()) {
            Novus = 1;
        }
        else {
            Novus = 0;
        }
        if(chkNimbus.isSelected()) {
            Nimbus = 1;
        }
        else {
            Nimbus = 0;
        }
        if(chkODS.isSelected()) {
            ODS = 1;
        }
        else {
            ODS = 0;
        }
        if(chkRDV.isSelected()) {
            RDV = 1;
        }
        else {
            RDV = 0;
        }
        if(chkVision.isSelected()) {
            Vision = 1;
        }
        else {
            Vision = 0;
        }
        if(chkUnison.isSelected()) {
            Unison = 1;
        }
        else {
            Unison = 0;
        }
        if(chkOthers.isSelected()) {
            Others = 1;
        }
        else {
            Others = 0;
        }
        if(tglRemember.isSelected())
        remember_me = 1;
        else{
        remember_me = 0;
        }
         
                prgLoader.setValue(50);
                jLabel9.setText("50%");
                
                DatabaseConnection d = new DatabaseConnection(ip_address,user,password,database_name,database_type);
                new Thread(d).start();
                if(d.flag == true){
                   prgLoader.setValue(100);
                   jLabel9.setText("100%");
                   this.setVisible(false);
                   new DataFrame().setVisible(true);
                }
                else {
                   prgLoader.setValue(100);
                   jLabel9.setText("100%");
                   JOptionPane.showMessageDialog(this, "Error Occured.","Alert",JOptionPane.ERROR_MESSAGE);
                }
                 prgLoader.setVisible(false);

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnPingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPingActionPerformed
        // TODO add your handling code here:
        
        prgLoader.setVisible(true);
        prgLoader.setValue(10);
        
        String ip = txtServer.getText().toString();
        if(!ip.equals("")){
              System.out.println(ip);
              try {
                  Thread.yield();
                  InetAddress address = InetAddress.getByName(ip);
                  System.out.println("Name: " + address.getHostName());
                  System.out.println("Addr: " + address.getHostAddress());
                  System.out.println("Reach: " + address.isReachable(3000));
                  Thread.yield();
                  ip_address = address.getHostName();
                  if(address.isReachable(3000) == true) { 
                      prgLoader.setValue(100);
                       JOptionPane.showMessageDialog(this, address.getHostName()+" is successfully ping.","Alert",JOptionPane.INFORMATION_MESSAGE);
                  }
                  else {
                       prgLoader.setValue(100);
                       JOptionPane.showMessageDialog(this, address.getHostName()+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
                  }
                  }
              catch (UnknownHostException e) {
                  System.err.println("Unable to lookup "+ip);
                  System.out.println("Details: "+e.getMessage());
                  JOptionPane.showMessageDialog(this, ip+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
               }
              catch (IOException e) {
                  System.err.println("Unable to reach "+ip);
                  System.out.println("Details: "+e.getMessage());
                  JOptionPane.showMessageDialog(this, ip_address+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
               }
        }
        else {
               prgLoader.setValue(100);
               JOptionPane.showMessageDialog(this, "Please Enter an IP Address or a Hostname.","Alert",JOptionPane.ERROR_MESSAGE);
        }
        
        prgLoader.setVisible(false);
    }//GEN-LAST:event_btnPingActionPerformed

    private void txtServerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServerKeyPressed
        // TODO add your handling code here:
        System.out.println(evt.getKeyCode());
        if(evt.getKeyCode() == 10){
           String ip = txtServer.getText().toString();
        if(!ip.equals("")){
              System.out.println(ip);
              try {
                  InetAddress address = InetAddress.getByName(ip);
                  System.out.println("Name: " + address.getHostName());
                  System.out.println("Addr: " + address.getHostAddress());
                  System.out.println("Reach: " + address.isReachable(3000));
                  Thread.yield();
                  ip_address = address.getHostName();
                  if(address.isReachable(3000) == true)
                       JOptionPane.showMessageDialog(this, address.getHostName()+" is successfully ping.","Alert",JOptionPane.INFORMATION_MESSAGE);
                  else
                       JOptionPane.showMessageDialog(this, address.getHostName()+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
                  }
              catch (UnknownHostException e) {
                  System.err.println("Unable to lookup "+ip);
                  System.out.println("Details: "+e.getMessage());
                  JOptionPane.showMessageDialog(this, ip+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
               }
              catch (IOException e) {
                  System.err.println("Unable to reach "+ip);
                  System.out.println("Details: "+e.getMessage());
                  JOptionPane.showMessageDialog(this, ip_address+" cannot be reached.","Alert",JOptionPane.ERROR_MESSAGE);
               }
        }
        else {
               JOptionPane.showMessageDialog(this, "Please Enter an IP Address or a Hostname.","Alert",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_txtServerKeyPressed

    private void tglRememberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglRememberActionPerformed
        // TODO add your handling code here:
        if(tglRemember.isSelected()){
        tglRemember.setBackground(Color.GREEN);
        tglRemember.setText("ON");
        }
        else {
        tglRemember.setBackground(Color.LIGHT_GRAY);
        tglRemember.setText("OFF");
        }
    }//GEN-LAST:event_tglRememberActionPerformed

    private void btnImageChanger1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageChanger1ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src//PCPlus.png");
        jLabel11.setIcon(icon);
        Thread.yield();
        btnImageChanger1.setBackground(Color.GREEN);
        btnImageChanger2.setBackground(Color.WHITE);
        btnImageChanger3.setBackground(Color.WHITE);
        btnImageChanger1.setFocusable(true);
        btnImageChanger2.setFocusable(true);
        btnImageChanger3.setFocusable(true);
        btnImageChanger1.setVisible(true);
        btnImageChanger2.setVisible(true);
        btnImageChanger3.setVisible(true);
    }//GEN-LAST:event_btnImageChanger1ActionPerformed

    private void btnImageChanger2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageChanger2ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src//DBGear.png");
        jLabel11.setIcon(icon);
        Thread.yield();
        btnImageChanger1.setBackground(Color.WHITE);
        btnImageChanger2.setBackground(Color.GREEN);
        btnImageChanger3.setBackground(Color.WHITE);
        btnImageChanger1.setFocusable(true);
        btnImageChanger2.setFocusable(true);
        btnImageChanger3.setFocusable(true);
    }//GEN-LAST:event_btnImageChanger2ActionPerformed

    private void btnImageChanger3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageChanger3ActionPerformed
        // TODO add your handling code here:
        ImageIcon icon = new ImageIcon("src//HC6_1.png");
        jLabel11.setIcon(icon);
        Thread.yield();
        btnImageChanger1.setBackground(Color.WHITE);
        btnImageChanger2.setBackground(Color.WHITE);
        btnImageChanger3.setBackground(Color.GREEN);
        btnImageChanger1.setFocusable(true);
        btnImageChanger2.setFocusable(true);
        btnImageChanger3.setFocusable(true);
    }//GEN-LAST:event_btnImageChanger3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnImageChanger1;
    private javax.swing.JButton btnImageChanger2;
    private javax.swing.JButton btnImageChanger3;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPing;
    private javax.swing.JCheckBox chkAmbit;
    private javax.swing.JCheckBox chkAmbitCor;
    private javax.swing.JCheckBox chkMobile;
    private javax.swing.JCheckBox chkNimbus;
    private javax.swing.JCheckBox chkNovus;
    private javax.swing.JCheckBox chkODS;
    private javax.swing.JCheckBox chkOthers;
    private javax.swing.JCheckBox chkRDV;
    private javax.swing.JCheckBox chkUnison;
    private javax.swing.JCheckBox chkVision;
    private javax.swing.JComboBox comboDatabaseType;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JLabel lblDatabaseName;
    private javax.swing.JLabel lblDatabaseType;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblRemember;
    private javax.swing.JLabel lblServer;
    private javax.swing.JLabel lblUser;
    private javax.swing.JProgressBar prgLoader;
    private javax.swing.JToggleButton tglRemember;
    private javax.swing.JTextField txtDatabaseName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtServer;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}

